[4/4 EIP 4844 in inserter circuit] prover: insertion_circuit: implement EIP 4844
reilabs/semaphore-mtb pull request #14
Opened 2024-06-13 22:04 UTC by wzmuda

# This is patch 4/4 of the EIP 4844 in inserter circuit

Modify the inserter circuit to accept 4844 commitment and perform evaluation of its genuineness.

2024-06-21 14:29 UTC, kustosz requested changes

2024-06-21 14:29 UTC, kustosz commented on prover/insertion_circuit.go
> +		omegasToI[bits.Reverse64(uint64(i))>>52] = emulated.ValueOf[Fr](omegaToI)
this index manipulation should be extracted to a documented function (taking log of degree as an argument), can call it `bitReversedIndex`

2024-06-21 14:29 UTC, kustosz commented on prover/insertion_circuit.go
> +	evaluationValue = api.FromBinary(field.ToBits(&y)...)
`field.ToBits` is allowed to return different length results, leading to non-determinism here. You should ascertain that the returned bits are the unique smallest rep (if it already is, you should assert it)

2024-06-21 14:29 UTC, kustosz commented on prover/insertion_circuit.go
> +		api, ToReducedBigEndian{
You can get rid of `ToReducedBigEndian` (specifically the `reduced` part – gnark 10 can do it on its own now)

2024-06-21 14:29 UTC, kustosz commented on prover/insertion_circuit.go
> +	copy(paddedIdComms, circuit.IdComms)
this can probably be done smarter (without double traversal?)

2024-06-21 14:29 UTC, kustosz commented on prover/insertion_circuit.go
> +		api, ToReducedBigEndian{
again, `ToReducedBigEndian` can die

2024-06-23 20:35 UTC, wzmuda commented on prover/insertion_circuit.go
> +	evaluationValue = api.FromBinary(field.ToBits(&y)...)
I don't understand why it matters here if we immediately create `frontend.Variable` from bits so the value will be reduced anyway.

2024-06-23 20:37 UTC, wzmuda commented on prover/insertion_circuit.go
> +		api, ToReducedBigEndian{
I got rid of the internal reduction because indeed this should be taken care of by gnark when using `frontend.Variable`. However I don't see how we can get rid of the rest of it. We have `api.ToBinary` but it returns the result in LE.

2024-06-23 20:37 UTC, wzmuda commented on prover/insertion_circuit.go
> +		omegasToI[bits.Reverse64(uint64(i))>>52] = emulated.ValueOf[Fr](omegaToI)
Fixed

2024-06-25 14:22 UTC, kustosz commented on prover/insertion_circuit.go
> +	evaluationValue = api.FromBinary(field.ToBits(&y)...)
`ToBits` returns a value equivalent modulo the emulated prime, `FromBinary` modulo the native prime. I'll give you an example – let's say native field is 17 and emulated is 19. Let's take the value 15. If you take the smallest rep, you'll get 15 after this chain. But modulo 19 we also have 15 = 19 + 15 = 34. But if we reduce modulo 17, it is 0 (which is very different from 15).

2024-06-25 14:23 UTC, kustosz commented on prover/insertion_circuit.go
> +		api, ToReducedBigEndian{
Yes, the BigEndian part needs to stay, but the reduction can go

2024-06-25 15:04 UTC, wzmuda commented on prover/insertion_circuit.go
> +		api, ToReducedBigEndian{
so is this enough? https://github.com/reilabs/semaphore-mtb/pull/14/commits/17f5529ff4f79109d9fa0ca12a065154a41819d4 or would you like to see some more refactoring?

2024-06-25 22:54 UTC, wzmuda commented on prover/insertion_circuit.go
> +	copy(paddedIdComms, circuit.IdComms)
It's smarter now. Not sure if the smartestest possible but I wanted to append zero-elements to circuit.IdComms and that throws an error, that compilation is not deterministic. So it looks like we must have a separate padded slice but we don't have to iterate over all of it but just over the extra elements to initialize them, like this https://github.com/reilabs/semaphore-mtb/pull/14/commits/0c010d9ebd7581072303d83844be07fe0301d80b

2024-06-27 14:18 UTC, kustosz approved these changes

2024-06-29 08:37 UTC, merged